#!/bin/ash
# 
# This script rotates logs generated by squid
# and format them as csv
# Especially useful to format BUMPED data
# This script is meant to be executed by a crontab every 5 mins
# in order to keep file sizes manageable
# 0-59/5* * * * * /opt/a2m/crontab-not-connected.sh 
# Needs  a BUMP-enabled squid installed
# with the following logformat configured in squid.conf
# logformat a2m  %{%Y/%m/%d %H:%M:%S}tl|%>a|%rm|"%ru"

#
# Antonio Gonzalez aggarcia@gmail.com
# Oct 2020, the year of covid


ROTATED_FILE=/tmp/squid_access.log.0
OUTFILE=/tmp/squiddata-$DATE.csv

#force squid to rotate log file
/usr/sbin/squid -k rotate

#wait for the file to be closed
while [ ! -f $ROTATED_FILE ]; do
  sleep 1
done


#write csv headers
LO="publicIp,timestamp,ip,method,url,mac,friendlyName"
echo $LO > $OUTFILE

# service to get external IP
PUBLICIP=$(curl ifconfig.me)

while read line; do 
  cut1="${line%|*}"
  ip="${cut1#*|}"
  ip="${ip%|*}"
  salida="${line//,/%2C}"
  salida="${salida//|/,}"
  # don't want anonymous data, only the ones with explicit ip
  if [ $ip != '-' ]; then 
    mac=$(grep "$ip " /proc/net/arp|tr -s ' '|cut -d' ' -f4)
    #substitute whitespaces with commas
    wof=$(echo $data $mac |sed 's/ /,/g')
    #extract friendly name from leases
    friendly=$(grep $mac /tmp/dhcp.leases|cut -d' ' -f4 )

    echo "$PUBLICIP,$salida,$mac,$friendly">> $OUTFILE
  fi
done < $ROTATED_FILE

rm $ROTATED_FILE
